-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgLyezkZRKxW4ETLvb
uW9MAQFdjouZyf9DTaTVM2If+rGgCgYIKoZIzj0DAQehRANCAARdQqi3XOHv4pUu
BOHvhJi9hquO3V/3GLiXM2Dw0b5f+AP4BI0kIMlKepu/HD7DY0K+SKyXyKud6h0g
52ruJPpe
-----END PRIVATE KEY-----